### ISSUE TITLE
Ne clique pas sur "Rejoindre" ou Accepter

### ISSUE THREAD

**Issue by hutigh** [Dfarm-Tools/DFarm#1]
Salut ! 

Quand je lance le bouton groupe, il ne veux ni cliquer sur le chat pour lancer la commande ni accepter .
Or quand le bouton accepter n'y est pas par exemple il clique bien sur l'emplacement où devrais ce situer le bouton.

Vous auriez une idée pour régler mon problème ?

**Comment by Dfarm-Tools** [comment]
Fix avec ce commit : https://github.com/Dfarm-Tools/DFarm/commit/84f55c21c75212549ccf330e810125010d38f2b0 

VOUS DEVEZ REFAIRE LES POSITIONS AVEC LE TOOL CURSEUR
