### ISSUE TITLE
Erreur ligne 52 conf.ini

### ISSUE THREAD

**Issue by hutigh** [Dfarm-Tools/DFarm#2]
Salut, 

J'ai vu que tu avais mis à jour Dfarm mais que tu ne parlais plus trop sur discord donc je me permet de te faire part de mon bug depuis la maj que tu as faite ici ! :)

https://cdn.discordapp.com/attachments/921461268781596762/1018540650980986990/Capture_decran_2022-09-11_171645.png

**Comment by CharlesBinard** [comment]
Effectivement, je viens de mettre a jour le .exe de la version 1.0.3
